sonar.projectKey=VibeJournal
sonar.projectName=VibeJournal
sonar.sources=app,features,lib,prisma
sonar.exclusions=.next/**,out/**,node_modules/**,coverage/**,dist/**,build/**,*.config.js,*.config.mjs,*.config.ts,**/*.d.ts
sonar.coverage.exclusions=app/**,features/**,lib/**,prisma/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
